---
layout: cv
title: Tamanna Sangroula's CV
---
# Tamanna Sangroula
Undergraduate Student at BYU-Idaho, Accounting major, Data Science Minor.

<div id="webaddress">
 <a href="www.linkedin.com/in/tamanna-sangroula-aa8977293">My LinkedIn</a>
</div>


## Summary

Detail-oriented Accounting Major with a Data Science minor having a strong academic foundation and a passion for financial analysis and reporting.
Proficient in manual accounting processes and committed to upholding the highest standards of accuracy and ethics. Skilled in reconciling complex accounts and identifying discrepancies. Adept at collaborating with cross-functional teams to streamline processes and improve financial performance. Seeking opportunities to leverage academic knowledge in a professional accounting role.

## Skills

• Programming Skills: Python, SQL.<br>
• Accounting Skills: Financial Reporting, Book Keeping, Financial Analysis.<br>
• Computer Skills: MS. Excel, MS. Powerpoint, MS. Word.<br>
• Soft Skills: Problem Solving, Teamwork, Ethical Conduct, Leadership, Communication, Adaptability.

## Experience

`University Of Louisian at Monroe - Student worker; Monroe, LA` | `January 2023 - May 2023`<br>
• Facilitated technology use for over 200 library visitors monthly, resolving 95% of equipment issues, and providing guidance for
accessing digital resources and databases, enhancing patron's overall library experience.<br>
• Took active roles in 20+ annual library programs, contributed to 15+ promotional materials and displays, and participated in 10+
training and professional development sessions.

## Education

`January 2022 - May 2023`
__University of Louisian at Monroe.__

`September 2023 - now`
__Bragham Young University, Idaho__



## Awards

`2022`
ULM Emerging Scholar, University of Louisiana at Monroe.



<!-- ### Footer

Last updated: May 2013 -->